name: Docker Build and Push

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4.1.1

    - name: Log in Into Docker Hub
      run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin}}"
      
    - name: Build and Push Docker Image
      run: |
        docker build -t "${{ secrets.DOCKERHUB_USERNAME }}/nextresult-gitAction:latest"
        docker push "${{ secrets.DOCKERHUB_USERNAME }}/nextresult-gitAction:latest"
        
